osx_image: xcode9.1
language: objective-c

env:
  global:
    - PROJECT_NAME="swift-httpdate"

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - xcodebuild test -project "$PROJECT_NAME.xcodeproj" -scheme $PROJECT_NAME -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' | xcpretty
  - bash <(curl -s https://codecov.io/bash)
